import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Helper from "@/utils/Helper";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "@/Context/AuthContext";
const inter = Inter({ subsets: ["latin"] });
import "flowbite";
import { ThemeProvider } from "@/Context/ThemeContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head></head>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <AuthProvider>
            <Helper />
            {children}
            <Toaster />
          </AuthProvider>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.js"></script>
        </ThemeProvider>
      </body>
    </html>
  );
}
